image: node:latest

cache:
  paths:
    - node_modules

before_script:
  - yarn global add typescript tslint
  - yarn install

stages:
  - lint
  - build

linting:
  stage: lint
  script:
    - tslint .

compiling:
  stage: build
  script:
    - tsc
    - mkdir out/languages
    - cp src/languages/*.json out/languages/
    - cp src/*.sh out/
    - cp package.json out/
    - cp node_modules out/
  artifacts:
    untracked: true
    paths:
      - out