image: node:latest

cache:
  paths:
    - node_modules

before_script:
  - yarn global add typescript tslint grunt-cli
  - yarn install

stages:
  - build

compiling:
  stage: build
  script:
    - grunt
  artifacts:
    untracked: true
    paths:
      - out