image: node:latest

cache:
  paths:
    - node_modules

before_script:
  - npm install -g grunt-cli
  - npm install

stages:
  - build

compiling:
  stage: build
  script:
    - grunt
  artifacts:
    untracked: true
    paths:
      - out
